name: Update Instances
concurrency: osb-instances # signal that we're modifying instances (status/gemerated tf=)

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  GITHUB_TOKEN: ${{ secrets.GH_USER_TOKEN }}
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

on:
  # run on any push to master
  push:
    branches:
      - "master"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  process-services:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: meshcloud/setup-unipipe@v1
      - uses: hashicorp/setup-terraform@v1
      - uses: actions/checkout@v3
      ### Doing actual VNet Stuff
      - name: Prepare terraform files
        run: |
          unipipe --version
          unipipe list
          unipipe transform --registry-of-handlers=network/handlers.js
          unipipe transform --registry-of-handlers=github-service/handlers.js
      - name: Configure git for VNet Bot
        run: |
          git config --global user.email "azure-platform-operators@example.com"
          git config --global user.name "VNet Bot by example.com"
      - name: Create Repositories
        continue-on-error: true
        run: |
          git checkout master
          cd github-service
          chmod +x create.sh
          ./create.sh
          cd ..
          git add .
          git diff-index --quiet HEAD || git commit -m "Updating GitHub Services"
          git push
      - name: Create VNETs
        continue-on-error: true
        run: |
          git checkout master
          cd network
          chmod +x create.sh
          ./create.sh
          cd ..
          git add .
          git diff-index --quiet HEAD || git commit -m "Updating VNets"
          git push
